### ISSUE TITLE
403 errors on Centos7, RHEL7

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-sonarqube#6]
##### SUMMARY

Nginx config doesn't work correctly on Centos 7.
SonarQube is not available, errors in log:
`2018/08/30 15:43:53 [error] 3188#3188: *1 open() "/app/sonarqube/sonarqube-7.2.1/web/js/vendors~main.4d5eb46f.chunk.js" failed (13: Permission denied), client: 86.57.255.91, server: ec2-34-252-95-174.eu-west-1.compute.amazonaws.com, request: "GET /js/vendors~main.4d5eb46f.chunk.js HTTP/1.1", host: "ec2-34-252-95-174.eu-west-1.compute.amazonaws.com", referrer: "https://ec2-34-252-95-174.eu-west-1.compute.amazonaws.com/"
2018/08/30 15:43:53 [error] 3188#3188: *3 open() "/app/sonarqube/sonarqube-7.2.1/web/js/main.10c651b9.js" failed (13: Permission denied), client: 86.57.255.91, server: ec2-34-252-95-174.eu-west-1.compute.amazonaws.com, request: "GET /js/main.10c651b9.js HTTP/1.1", host: "ec2-34-252-95-174.eu-west-1.compute.amazonaws.com", referrer: "https://ec2-34-252-95-174.eu-west-1.compute.amazonaws.com/"`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nginx config

##### ANSIBLE VERSION

```

```

##### OS / ENVIRONMENT

Centos 7

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by dzmitry-rudnouski** [comment]
Workaround:
Comment following lines in /etc/nginx/conf.d/sonar.conf:
`    location ~* .(css|gif|html|ico|jpeg|js|map|png|svg|txt|xml)$ {
      root /app/sonarqube/sonarqube-7.2.1/web;
    }
`

**Comment by dzmitry-rudnouski** [comment]
Temp workaround added to release 1.1.

**Comment by tgadiev** [comment]
@dzmitry-rudnouski Is it still present?
