### ISSUE TITLE
413 Request Entity Too Large - from nginx, during sending report to SonarQube

### ISSUE THREAD

**Issue by DmitriyStoyanov** [lean-delivery/ansible-role-sonarqube#7]
##### SUMMARY

Because of default limitation of nginx proxy server we are facing with next error during SonarQube Analisys:
`
09:18:16.772 DEBUG: Upload report
09:18:18.378 DEBUG: POST 413 http://***/api/ce/submit?projectKey=*** | time=1605ms
09:18:18.494 INFO: ------------------------------------------------------------------------
09:18:18.499 INFO: EXECUTION FAILURE
09:18:18.499 INFO: ------------------------------------------------------------------------
09:18:18.500 INFO: Total time: 5:15.441s
09:18:18.633 INFO: Final Memory: 45M/560M
09:18:18.635 INFO: ------------------------------------------------------------------------
09:18:18.635 ERROR: Error during SonarQube Scanner execution
09:18:18.636 ERROR: Failed to upload report - 413: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.3</center>
</body>
</html>
`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nginx

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by dzmitry-rudnouski** [comment]
Fixed in release 1.1.
