### ISSUE TITLE
Add ability to set up ulimit for sonar user

### ISSUE THREAD

**Issue by artyom-gatalsky** [lean-delivery/ansible-role-sonarqube#9]
https://docs.sonarqube.org/display/SONAR/Requirements#Requirements-Linux

If you're running on Linux, you must ensure that:

vm.max_map_count is greater or equals to 262144
fs.file-max is greater or equals to 65536
the user running SonarQube can open at least 65536 file descriptors
the user running SonarQube can open at least 2048 threads

**Comment by dzmitry-rudnouski** [comment]
File descriptors and threads done in release 1.3.

**Comment by dzmitry-rudnouski** [comment]
vm.max_map_count is covered in vm.max_map_count

**Comment by tgadiev** [comment]
Fixed by #323
